/**
 * Riso ink database with spectral metadata for color separation.
 *
 * Hex strings are the hand-authored source; `rgb` (RgbU32) is the packed
 * form used everywhere downstream. `kBands` / `baseline` / `kScale` /
 * `fluorescence` feed the Kubelka-Munk solver, which calibrates kScale and
 * the per-band amplitudes against the published hex at module load.
 * `mixingMethod` is advisory: `alpha_blend_only` inks have synthesized
 * (hex_synthesized) K-bands that approximate single-ink color but are
 * unreliable for overprint physics.
 *
 * A few inks share an rgb (wine ↔ burgundy, tomato ↔ marine red, raspberry
 * red ↔ cranberry). These collide as keys in the downstream colors map, so
 * INKS_BY_RGB keeps the first occurrence; the alternate entries stay in
 * INKS so their distinct K-bands remain available for ID-based lookup.
 */

import { hexToRgb, type RgbU32 } from "../utils/color";
import {
  calibrateKScale,
  type FluorescenceParams,
  type KBand,
} from "../utils/spectral";

export type { FluorescenceParams, KBand };

export type Confidence = "certain" | "high" | "medium" | "low" | "fluorescent";

export type MixingMethod =
  | "kubelka_munk"
  | "kubelka_munk_fluorescent"
  | "alpha_blend_only"
  | "transparent";

export type KBandsSource =
  | "pigment_template"
  | "hex_synthesized"
  | "transparent_extender"
  | "measured";

/** Max calibrated ΔE between predicted-at-α=1 and the ink's published hex
 * for KM mode to be offered. Fluorescent inks get a looser bound because
 * the gaussian Stokes-shift approximation is inherently crude. */
const KM_ELIGIBILITY_DELTA_E_NON_FLUOR = 5;
const KM_ELIGIBILITY_DELTA_E_FLUOR = 10;

interface InkRaw {
  readonly id: string;
  readonly name: string;
  readonly hex: string;
  readonly confidence: Confidence;
  readonly mixingMethod: MixingMethod;
  readonly pigmentGuess?: string;
  readonly pigmentNotes?: string;
  readonly kBands?: readonly KBand[];
  readonly kBandsSource?: KBandsSource;
  readonly baseline?: number;
  readonly kScale?: number;
  readonly fluorescence?: FluorescenceParams;
  readonly notes?: string;
}

export interface Ink extends InkRaw {
  readonly rgb: RgbU32;
  /** kScale after calibration to match the published hex at α=1. */
  readonly kScale: number;
  /** ΔE between calibrated KM prediction and target hex; lower is better. */
  readonly kmDeltaE: number;
  /** True when the calibrated KM prediction is within tolerance of the hex.
   *  Inks where this is false should not be available in KM mode. */
  readonly kmEligible: boolean;
}

// more riso colors: https://www.stencil.wiki/colors
const INKS_RAW: readonly InkRaw[] = [
  {
    id: "burgundy",
    name: "burgundy",
    hex: "#914e72",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PV19 + PR254 + PBk7",
    pigmentNotes: "Deep wine red; aliased with wine",
    kBands: [
      { center: 570, width: 65, amplitude: 1.0 },
      { center: 440, width: 50, amplitude: 0.3 },
      { center: 550, width: 1000, amplitude: 0.3 },
    ],
    baseline: 0.03,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "violet",
    name: "violet",
    hex: "#9d7ad2",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PV23",
    pigmentNotes: "Dioxazine violet",
    kBands: [
      { center: 580, width: 60, amplitude: 1.0 },
      { center: 380, width: 30, amplitude: 0.3 },
    ],
    baseline: 0.03,
    kScale: 6.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "orchid",
    name: "orchid",
    hex: "#aa60bf",
    confidence: "low",
    mixingMethod: "alpha_blend_only",
    pigmentGuess: "PV19 + PV23 + PW6",
    pigmentNotes: "Light purple-pink",
    kBands: [
      { center: 620, width: 50, amplitude: 0.333 },
      { center: 530, width: 50, amplitude: 0.624 },
      { center: 440, width: 50, amplitude: 0.251 },
    ],
    baseline: 0.02,
    kScale: 2.61,
    kBandsSource: "hex_synthesized",
  },
  {
    id: "plum",
    name: "plum",
    hex: "#845991",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PV23 + PBk7",
    pigmentNotes: "Darker dioxazine violet",
    kBands: [
      { center: 580, width: 60, amplitude: 1.0 },
      { center: 380, width: 30, amplitude: 0.3 },
      { center: 550, width: 1000, amplitude: 0.3 },
    ],
    baseline: 0.03,
    kScale: 6.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "purple",
    name: "purple",
    hex: "#765ba7",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PV23 + PB29",
    pigmentNotes: "Dioxazine violet + ultramarine",
    kBands: [
      { center: 580, width: 60, amplitude: 1.0 },
      { center: 380, width: 30, amplitude: 0.2 },
      { center: 600, width: 80, amplitude: 0.3 },
      { center: 380, width: 30, amplitude: 0.06 },
    ],
    baseline: 0.039,
    kScale: 6.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "raisin",
    name: "raisin",
    hex: "#775d7a",
    confidence: "low",
    mixingMethod: "alpha_blend_only",
    pigmentGuess: "PV23 + PBk7 + PR254",
    pigmentNotes: "Muted dark purple",
    kBands: [
      { center: 620, width: 50, amplitude: 0.533 },
      { center: 530, width: 50, amplitude: 0.635 },
      { center: 440, width: 50, amplitude: 0.522 },
    ],
    baseline: 0.02,
    kScale: 3.25,
    kBandsSource: "hex_synthesized",
  },
  {
    id: "grape",
    name: "grape",
    hex: "#6c5d80",
    confidence: "low",
    mixingMethod: "alpha_blend_only",
    pigmentGuess: "PV23 + PB29 + PBk7",
    pigmentNotes: "Dark purple, blue-leaning",
    kBands: [
      { center: 620, width: 50, amplitude: 0.576 },
      { center: 530, width: 50, amplitude: 0.635 },
      { center: 440, width: 50, amplitude: 0.498 },
    ],
    baseline: 0.02,
    kScale: 3.28,
    kBandsSource: "hex_synthesized",
  },
  {
    id: "aqua",
    name: "aqua",
    hex: "#5ec8e5",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PB15:3 + PG7 (cyan-bias)",
    pigmentNotes: "Cyan with green shift",
    kBands: [
      { center: 620, width: 50, amplitude: 1.0 },
      { center: 690, width: 30, amplitude: 0.7 },
      { center: 380, width: 50, amplitude: 0.3 },
      { center: 600, width: 60, amplitude: 0.3 },
      { center: 700, width: 40, amplitude: 0.18 },
      { center: 410, width: 40, amplitude: 0.18 },
    ],
    baseline: 0.026,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "cornflower",
    name: "cornflower",
    hex: "#62a8e5",
    confidence: "low",
    mixingMethod: "alpha_blend_only",
    pigmentGuess: "PB15:3 + PB29",
    pigmentNotes: "Phthalo with ultramarine character",
    kBands: [
      { center: 620, width: 50, amplitude: 0.616 },
      { center: 530, width: 50, amplitude: 0.341 },
      { center: 440, width: 50, amplitude: 0.102 },
    ],
    baseline: 0.02,
    kScale: 2.41,
    kBandsSource: "hex_synthesized",
  },
  {
    id: "skyblue",
    name: "skyblue",
    hex: "#4982cf",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PB15:3 (diluted) + PW6",
    pigmentNotes: "Phthalo blue tint",
    kBands: [
      { center: 620, width: 50, amplitude: 1.0 },
      { center: 690, width: 30, amplitude: 0.7 },
      { center: 380, width: 50, amplitude: 0.3 },
      { center: 400, width: 30, amplitude: 0.12 },
    ],
    baseline: 0.02,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "sea-blue",
    name: "sea blue",
    hex: "#0074a2",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PB15:3 + PB36",
    pigmentNotes: "Phthalo blue, slightly greener",
    kBands: [
      { center: 620, width: 50, amplitude: 1.0 },
      { center: 690, width: 30, amplitude: 0.7 },
      { center: 380, width: 50, amplitude: 0.3 },
      { center: 600, width: 60, amplitude: 0.2 },
      { center: 700, width: 40, amplitude: 0.12 },
      { center: 410, width: 40, amplitude: 0.12 },
    ],
    baseline: 0.024,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "blue",
    name: "blue",
    hex: "#0078bf",
    confidence: "high",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PB15:3",
    pigmentNotes: "Standard process blue; phthalocyanine beta form",
    kBands: [
      { center: 620, width: 50, amplitude: 1.0 },
      { center: 690, width: 30, amplitude: 0.7 },
      { center: 380, width: 50, amplitude: 0.3 },
    ],
    baseline: 0.02,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "lake",
    name: "lake",
    hex: "#235ba8",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PB15:3 + PV23",
    pigmentNotes: "Phthalo with violet, more purple than medium blue",
    kBands: [
      { center: 620, width: 50, amplitude: 1.0 },
      { center: 690, width: 30, amplitude: 0.7 },
      { center: 380, width: 50, amplitude: 0.3 },
      { center: 580, width: 60, amplitude: 0.3 },
      { center: 380, width: 30, amplitude: 0.09 },
    ],
    baseline: 0.029,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "medium-blue",
    name: "medium blue",
    hex: "#3255a4",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PB15:3 + PV23",
    pigmentNotes: "Phthalo blue with violet shading",
    kBands: [
      { center: 620, width: 50, amplitude: 1.0 },
      { center: 690, width: 30, amplitude: 0.7 },
      { center: 380, width: 50, amplitude: 0.3 },
      { center: 580, width: 60, amplitude: 0.2 },
      { center: 380, width: 30, amplitude: 0.06 },
    ],
    baseline: 0.026,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "riso-federal-blue",
    name: "riso federal blue",
    hex: "#3d5588",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PB29 + PB15:3",
    pigmentNotes: "Ultramarine character dominant",
    kBands: [
      { center: 600, width: 80, amplitude: 1.0 },
      { center: 380, width: 30, amplitude: 0.2 },
      { center: 620, width: 50, amplitude: 0.3 },
      { center: 690, width: 30, amplitude: 0.21 },
      { center: 380, width: 50, amplitude: 0.09 },
    ],
    baseline: 0.036,
    kScale: 4.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "indigo",
    name: "indigo",
    hex: "#484d7a",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PB29 + PBk7",
    pigmentNotes: "Ultramarine darkened",
    kBands: [
      { center: 600, width: 80, amplitude: 1.0 },
      { center: 380, width: 30, amplitude: 0.2 },
      { center: 550, width: 1000, amplitude: 0.4 },
    ],
    baseline: 0.03,
    kScale: 4.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "midnight",
    name: "midnight",
    hex: "#435060",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PBk7 + PB15:3 + PB29",
    pigmentNotes: "Dark navy, mostly carbon black",
    kBands: [
      { center: 550, width: 1000, amplitude: 1.0 },
      { center: 620, width: 50, amplitude: 0.4 },
      { center: 690, width: 30, amplitude: 0.28 },
      { center: 380, width: 50, amplitude: 0.12 },
    ],
    baseline: 0.008,
    kScale: 50.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "steel",
    name: "steel",
    hex: "#375e77",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PB15:3 + PBk7",
    pigmentNotes: "Cool dark blue-gray",
    kBands: [
      { center: 620, width: 50, amplitude: 1.0 },
      { center: 690, width: 30, amplitude: 0.7 },
      { center: 380, width: 50, amplitude: 0.3 },
      { center: 550, width: 1000, amplitude: 0.4 },
    ],
    baseline: 0.02,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "smoky-teal",
    name: "smoky teal",
    hex: "#5f8289",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PG7 + PB15:3 + PBk7",
    pigmentNotes: "Muted teal, black-grayed",
    kBands: [
      { center: 600, width: 60, amplitude: 1.0 },
      { center: 700, width: 40, amplitude: 0.6 },
      { center: 410, width: 40, amplitude: 0.6 },
      { center: 550, width: 1000, amplitude: 0.3 },
    ],
    baseline: 0.02,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "spruce",
    name: "spruce",
    hex: "#4a635d",
    confidence: "low",
    mixingMethod: "alpha_blend_only",
    pigmentGuess: "PG7 + PBk7 (heavy)",
    pigmentNotes: "Very muted dark green",
    kBands: [
      { center: 620, width: 50, amplitude: 0.71 },
      { center: 530, width: 50, amplitude: 0.612 },
      { center: 440, width: 50, amplitude: 0.635 },
    ],
    baseline: 0.02,
    kScale: 3.61,
    kBandsSource: "hex_synthesized",
  },
  {
    id: "forest",
    name: "forest",
    hex: "#516e5a",
    confidence: "low",
    mixingMethod: "alpha_blend_only",
    pigmentGuess: "PG7 + PY150 + PBk7",
    pigmentNotes: "Darker, more yellow-leaning green",
    kBands: [
      { center: 620, width: 50, amplitude: 0.682 },
      { center: 530, width: 50, amplitude: 0.569 },
      { center: 440, width: 50, amplitude: 0.647 },
    ],
    baseline: 0.02,
    kScale: 3.53,
    kBandsSource: "hex_synthesized",
  },
  {
    id: "moss",
    name: "moss",
    hex: "#68724d",
    confidence: "low",
    mixingMethod: "alpha_blend_only",
    pigmentGuess: "PG7 + PY74 + PBk7",
    pigmentNotes: "Yellow-olive green muted",
    kBands: [
      { center: 620, width: 50, amplitude: 0.592 },
      { center: 530, width: 50, amplitude: 0.553 },
      { center: 440, width: 50, amplitude: 0.698 },
    ],
    baseline: 0.02,
    kScale: 3.46,
    kBandsSource: "hex_synthesized",
  },
  {
    id: "slate",
    name: "slate",
    hex: "#5e695e",
    confidence: "low",
    mixingMethod: "alpha_blend_only",
    pigmentGuess: "PG7 + PBk7",
    pigmentNotes: "Near-neutral cool gray",
    kBands: [
      { center: 620, width: 50, amplitude: 0.631 },
      { center: 530, width: 50, amplitude: 0.588 },
      { center: 440, width: 50, amplitude: 0.631 },
    ],
    baseline: 0.02,
    kScale: 3.47,
    kBandsSource: "hex_synthesized",
  },
  {
    id: "lagoon",
    name: "lagoon",
    hex: "#2f6165",
    confidence: "low",
    mixingMethod: "alpha_blend_only",
    pigmentGuess: "PG7 + PB15:3 + PBk7",
    pigmentNotes: "Dark muted teal",
    kBands: [
      { center: 620, width: 50, amplitude: 0.816 },
      { center: 530, width: 50, amplitude: 0.62 },
      { center: 440, width: 50, amplitude: 0.604 },
    ],
    baseline: 0.02,
    kScale: 3.72,
    kBandsSource: "hex_synthesized",
  },
  {
    id: "hunter-green",
    name: "hunter green",
    hex: "#407060",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PG7 + PBk7",
    pigmentNotes: "Phthalo darkened",
    kBands: [
      { center: 600, width: 60, amplitude: 1.0 },
      { center: 700, width: 40, amplitude: 0.6 },
      { center: 410, width: 40, amplitude: 0.6 },
      { center: 550, width: 1000, amplitude: 0.3 },
    ],
    baseline: 0.02,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "pine",
    name: "pine",
    hex: "#237e74",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PG7 + PG36",
    pigmentNotes: "Phthalo green family, darker",
    kBands: [
      { center: 600, width: 60, amplitude: 1.0 },
      { center: 700, width: 40, amplitude: 0.6 },
      { center: 410, width: 40, amplitude: 0.6 },
      { center: 610, width: 60, amplitude: 0.3 },
      { center: 700, width: 40, amplitude: 0.15 },
      { center: 410, width: 40, amplitude: 0.15 },
    ],
    baseline: 0.026,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "teal",
    name: "teal",
    hex: "#00838a",
    confidence: "high",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PB15:3 + PG7",
    pigmentNotes: "Phthalo blue + phthalo green",
    kBands: [
      { center: 620, width: 50, amplitude: 1.0 },
      { center: 690, width: 30, amplitude: 0.7 },
      { center: 380, width: 50, amplitude: 0.3 },
      { center: 600, width: 60, amplitude: 0.5 },
      { center: 700, width: 40, amplitude: 0.3 },
      { center: 410, width: 40, amplitude: 0.3 },
    ],
    baseline: 0.03,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "light-teal",
    name: "light teal",
    hex: "#009da5",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PB15:3 + PG7 (lighter)",
    pigmentNotes: "Same family, less concentrated",
    kBands: [
      { center: 620, width: 50, amplitude: 1.0 },
      { center: 690, width: 30, amplitude: 0.7 },
      { center: 380, width: 50, amplitude: 0.3 },
      { center: 600, width: 60, amplitude: 0.4 },
      { center: 700, width: 40, amplitude: 0.24 },
      { center: 410, width: 40, amplitude: 0.24 },
    ],
    baseline: 0.028,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "turquoise",
    name: "turquoise",
    hex: "#00aa93",
    confidence: "high",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PG7 + PB15:3",
    pigmentNotes: "Phthalo green dominant",
    kBands: [
      { center: 600, width: 60, amplitude: 1.0 },
      { center: 700, width: 40, amplitude: 0.6 },
      { center: 410, width: 40, amplitude: 0.6 },
      { center: 620, width: 50, amplitude: 0.5 },
      { center: 690, width: 30, amplitude: 0.35 },
      { center: 380, width: 50, amplitude: 0.15 },
    ],
    baseline: 0.03,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "seafoam",
    name: "seafoam",
    hex: "#62c2b1",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PG7 + PB15:3 + PW6",
    pigmentNotes: "Lighter mint variant",
    kBands: [
      { center: 600, width: 60, amplitude: 1.0 },
      { center: 700, width: 40, amplitude: 0.6 },
      { center: 410, width: 40, amplitude: 0.6 },
      { center: 620, width: 50, amplitude: 0.3 },
      { center: 690, width: 30, amplitude: 0.21 },
      { center: 380, width: 50, amplitude: 0.09 },
    ],
    baseline: 0.026,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "mint",
    name: "mint",
    hex: "#82d8d5",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PG7 + PB15:3 + PW6",
    pigmentNotes: "Phthalo mix, tinted",
    kBands: [
      { center: 600, width: 60, amplitude: 1.0 },
      { center: 700, width: 40, amplitude: 0.6 },
      { center: 410, width: 40, amplitude: 0.6 },
      { center: 620, width: 50, amplitude: 0.3 },
      { center: 690, width: 30, amplitude: 0.21 },
      { center: 380, width: 50, amplitude: 0.09 },
    ],
    baseline: 0.026,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "grass",
    name: "grass",
    hex: "#397e58",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PG7 + PY74 + PBk7",
    pigmentNotes: "Mid-tone yellow-green",
    kBands: [
      { center: 600, width: 60, amplitude: 1.0 },
      { center: 700, width: 40, amplitude: 0.6 },
      { center: 410, width: 40, amplitude: 0.6 },
      { center: 430, width: 35, amplitude: 0.5 },
      { center: 380, width: 30, amplitude: 0.35 },
    ],
    baseline: 0.025,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "emerald",
    name: "emerald",
    hex: "#19975d",
    confidence: "high",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PG7 + PY74",
    pigmentNotes: "Phthalo + yellow, brighter",
    kBands: [
      { center: 600, width: 60, amplitude: 1.0 },
      { center: 700, width: 40, amplitude: 0.6 },
      { center: 410, width: 40, amplitude: 0.6 },
      { center: 430, width: 35, amplitude: 0.5 },
      { center: 380, width: 30, amplitude: 0.35 },
    ],
    baseline: 0.025,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "ivy",
    name: "ivy",
    hex: "#169b62",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PG7 + PY74 + PBk7",
    pigmentNotes: "Slightly darkened green",
    kBands: [
      { center: 600, width: 60, amplitude: 1.0 },
      { center: 700, width: 40, amplitude: 0.6 },
      { center: 410, width: 40, amplitude: 0.6 },
      { center: 430, width: 35, amplitude: 0.3 },
      { center: 380, width: 30, amplitude: 0.21 },
    ],
    baseline: 0.023,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "green",
    name: "green",
    hex: "#00a95c",
    confidence: "high",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PG7 + PY74",
    pigmentNotes: "Phthalo green + Hansa yellow",
    kBands: [
      { center: 600, width: 60, amplitude: 1.0 },
      { center: 700, width: 40, amplitude: 0.6 },
      { center: 410, width: 40, amplitude: 0.6 },
      { center: 430, width: 35, amplitude: 0.5 },
      { center: 380, width: 30, amplitude: 0.35 },
    ],
    baseline: 0.025,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "kelly-green",
    name: "kelly green",
    hex: "#67b346",
    confidence: "high",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PG7 + PY74 (yellow-heavy)",
    pigmentNotes: "Yellow-leaning",
    kBands: [
      { center: 600, width: 60, amplitude: 1.0 },
      { center: 700, width: 40, amplitude: 0.6 },
      { center: 410, width: 40, amplitude: 0.6 },
      { center: 430, width: 35, amplitude: 0.7 },
      { center: 380, width: 30, amplitude: 0.49 },
    ],
    baseline: 0.027,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "fluorescent-green",
    name: "fluorescent green",
    hex: "#44d62c",
    confidence: "fluorescent",
    mixingMethod: "kubelka_munk_fluorescent",
    pigmentGuess: "fluorescent yellow-green dye",
    pigmentNotes: "Daylight fluorescent; Pyranine or fluorescent pigment lake",
    kBands: [
      { center: 470, width: 40, amplitude: 1.0 },
      { center: 380, width: 30, amplitude: 0.4 },
    ],
    baseline: 0.04,
    kScale: 5.0,
    fluorescence: {
      exCenter: 470,
      exWidth: 40,
      emCenter: 520,
      emWidth: 40,
      quantumYield: 0.7,
    },
    kBandsSource: "pigment_template",
  },
  {
    id: "light-lime",
    name: "light lime",
    hex: "#e3ed55",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PY74 + PG7 trace",
    pigmentNotes: "Yellow with green tint",
    kBands: [
      { center: 430, width: 35, amplitude: 1.0 },
      { center: 380, width: 30, amplitude: 0.7 },
      { center: 600, width: 60, amplitude: 0.1 },
      { center: 700, width: 40, amplitude: 0.06 },
      { center: 410, width: 40, amplitude: 0.06 },
    ],
    baseline: 0.012,
    kScale: 8.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "yellow",
    name: "yellow",
    hex: "#ffe800",
    confidence: "high",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PY74",
    pigmentNotes: "Hansa Yellow 5GX, standard print yellow",
    kBands: [
      { center: 430, width: 35, amplitude: 1.0 },
      { center: 380, width: 30, amplitude: 0.7 },
    ],
    baseline: 0.01,
    kScale: 8.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "fluorescent-yellow",
    name: "fluorescent yellow",
    hex: "#ffe916",
    confidence: "fluorescent",
    mixingMethod: "kubelka_munk_fluorescent",
    pigmentGuess: "fluorescent yellow dye",
    pigmentNotes: "Likely fluorescein-derivative or PY101 (Methine yellow)",
    kBands: [
      { center: 440, width: 35, amplitude: 1.0 },
      { center: 380, width: 30, amplitude: 0.5 },
    ],
    baseline: 0.03,
    kScale: 6.0,
    fluorescence: {
      exCenter: 440,
      exWidth: 35,
      emCenter: 510,
      emWidth: 40,
      quantumYield: 0.7,
    },
    kBandsSource: "pigment_template",
  },
  {
    id: "sunflower",
    name: "sunflower",
    hex: "#ffb511",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PY74 + PO34",
    pigmentNotes: "Yellow with orange shift",
    kBands: [
      { center: 430, width: 35, amplitude: 1.0 },
      { center: 380, width: 30, amplitude: 0.7 },
      { center: 480, width: 45, amplitude: 0.2 },
      { center: 400, width: 40, amplitude: 0.14 },
    ],
    baseline: 0.014,
    kScale: 8.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "melon",
    name: "melon",
    hex: "#ffae3b",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PY74 + PO34 (more orange)",
    pigmentNotes: "Orange-yellow",
    kBands: [
      { center: 430, width: 35, amplitude: 1.0 },
      { center: 380, width: 30, amplitude: 0.7 },
      { center: 480, width: 45, amplitude: 0.4 },
      { center: 400, width: 40, amplitude: 0.28 },
    ],
    baseline: 0.018,
    kScale: 8.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "apricot",
    name: "apricot",
    hex: "#f6a04d",
    confidence: "low",
    mixingMethod: "alpha_blend_only",
    pigmentGuess: "PY74 + PO34 + PR254 trace",
    pigmentNotes: "Peachy orange-yellow",
    kBands: [
      { center: 620, width: 50, amplitude: 0.035 },
      { center: 530, width: 50, amplitude: 0.373 },
      { center: 440, width: 50, amplitude: 0.698 },
    ],
    baseline: 0.02,
    kScale: 2.47,
    kBandsSource: "hex_synthesized",
  },
  {
    id: "paprika",
    name: "paprika",
    hex: "#ee7f4b",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PO34 + PR254",
    pigmentNotes: "Red-orange",
    kBands: [
      { center: 480, width: 45, amplitude: 1.0 },
      { center: 400, width: 40, amplitude: 0.7 },
      { center: 510, width: 50, amplitude: 0.3 },
      { center: 410, width: 50, amplitude: 0.15 },
    ],
    baseline: 0.029,
    kScale: 7.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "pumpkin",
    name: "pumpkin",
    hex: "#ff6f4c",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PO34 + PR254 (more red)",
    pigmentNotes: "Deep orange",
    kBands: [
      { center: 480, width: 45, amplitude: 1.0 },
      { center: 400, width: 40, amplitude: 0.7 },
      { center: 510, width: 50, amplitude: 0.4 },
      { center: 410, width: 50, amplitude: 0.2 },
    ],
    baseline: 0.032,
    kScale: 7.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "orange",
    name: "orange",
    hex: "#ff6c2f",
    confidence: "high",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PO34 + PY74",
    pigmentNotes: "Diarylide orange",
    kBands: [
      { center: 480, width: 45, amplitude: 1.0 },
      { center: 400, width: 40, amplitude: 0.7 },
      { center: 430, width: 35, amplitude: 0.3 },
      { center: 380, width: 30, amplitude: 0.21 },
    ],
    baseline: 0.023,
    kScale: 7.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "fluorescent-orange",
    name: "fluorescent orange",
    hex: "#ff7477",
    confidence: "fluorescent",
    mixingMethod: "kubelka_munk_fluorescent",
    pigmentGuess: "Rhodamine 6G or Acridine Orange",
    pigmentNotes: "Daylight fluorescent orange family",
    kBands: [
      { center: 490, width: 45, amplitude: 1.0 },
      { center: 400, width: 35, amplitude: 0.4 },
    ],
    baseline: 0.03,
    kScale: 5.0,
    fluorescence: {
      exCenter: 490,
      exWidth: 40,
      emCenter: 555,
      emWidth: 45,
      quantumYield: 0.7,
    },
    kBandsSource: "pigment_template",
  },
  {
    id: "coral",
    name: "coral",
    hex: "#ff8e91",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PR254 + PO34 + PW6",
    pigmentNotes: "Lighter, pink-orange",
    kBands: [
      { center: 510, width: 50, amplitude: 1.0 },
      { center: 410, width: 50, amplitude: 0.5 },
      { center: 480, width: 45, amplitude: 0.4 },
      { center: 400, width: 40, amplitude: 0.28 },
    ],
    baseline: 0.038,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "red",
    name: "red",
    hex: "#ff665e",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PR254 + PR170",
    pigmentNotes: "Red with slight blue undertone",
    kBands: [
      { center: 510, width: 50, amplitude: 1.0 },
      { center: 410, width: 50, amplitude: 0.5 },
      { center: 520, width: 55, amplitude: 0.3 },
      { center: 420, width: 50, amplitude: 0.18 },
    ],
    baseline: 0.039,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "bright-red",
    name: "bright red",
    hex: "#f15060",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PR254",
    pigmentNotes: "DPP Red, modern bright scarlet",
    kBands: [
      { center: 510, width: 50, amplitude: 1.0 },
      { center: 410, width: 50, amplitude: 0.5 },
    ],
    baseline: 0.03,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "crimson",
    name: "crimson",
    hex: "#e45d50",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PR254 + PV19",
    pigmentNotes: "Deep red with quinacridone violet",
    kBands: [
      { center: 510, width: 50, amplitude: 1.0 },
      { center: 410, width: 50, amplitude: 0.5 },
      { center: 570, width: 65, amplitude: 0.3 },
      { center: 440, width: 50, amplitude: 0.09 },
    ],
    baseline: 0.039,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "scarlet",
    name: "scarlet",
    hex: "#f65058",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PR254 + PO34",
    pigmentNotes: "Bright orange-red",
    kBands: [
      { center: 510, width: 50, amplitude: 1.0 },
      { center: 410, width: 50, amplitude: 0.5 },
      { center: 480, width: 45, amplitude: 0.3 },
      { center: 400, width: 40, amplitude: 0.21 },
    ],
    baseline: 0.036,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "tomato",
    name: "tomato",
    hex: "#d2515e",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PR254 + PO34",
    pigmentNotes: "Orange-red",
    kBands: [
      { center: 510, width: 50, amplitude: 1.0 },
      { center: 410, width: 50, amplitude: 0.5 },
      { center: 480, width: 45, amplitude: 0.3 },
      { center: 400, width: 40, amplitude: 0.21 },
    ],
    baseline: 0.036,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "marine-red",
    name: "marine red",
    hex: "#d2515e",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PR254 + PO34",
    pigmentNotes: "Alias of tomato (shares hex)",
    kBands: [
      { center: 510, width: 50, amplitude: 1.0 },
      { center: 410, width: 50, amplitude: 0.5 },
      { center: 480, width: 45, amplitude: 0.3 },
      { center: 400, width: 40, amplitude: 0.21 },
    ],
    baseline: 0.036,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "cranberry",
    name: "cranberry",
    hex: "#d1517a",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PV19 + PR254",
    pigmentNotes: "Quinacridone-dominant red-pink",
    kBands: [
      { center: 570, width: 65, amplitude: 1.0 },
      { center: 440, width: 50, amplitude: 0.3 },
      { center: 510, width: 50, amplitude: 0.4 },
      { center: 410, width: 50, amplitude: 0.2 },
    ],
    baseline: 0.042,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "maroon",
    name: "maroon",
    hex: "#9e4c6e",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PV19 + PR254 + PBk7",
    pigmentNotes: "Dark wine red",
    kBands: [
      { center: 570, width: 65, amplitude: 1.0 },
      { center: 440, width: 50, amplitude: 0.3 },
      { center: 550, width: 1000, amplitude: 0.3 },
    ],
    baseline: 0.03,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "wine",
    name: "wine",
    hex: "#914e72",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PV19 + PBk7",
    pigmentNotes: "Alias of burgundy (shares hex)",
    kBands: [
      { center: 570, width: 65, amplitude: 1.0 },
      { center: 440, width: 50, amplitude: 0.3 },
      { center: 550, width: 1000, amplitude: 0.3 },
    ],
    baseline: 0.03,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "dark-mauve",
    name: "dark mauve",
    hex: "#bd8ca6",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PV19 + PW6",
    pigmentNotes: "Quinacridone violet tinted",
    kBands: [
      { center: 570, width: 65, amplitude: 1.0 },
      { center: 440, width: 50, amplitude: 0.3 },
    ],
    baseline: 0.03,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "light-mauve",
    name: "light mauve",
    hex: "#e6b5c9",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PV19 + PW6 (more white)",
    pigmentNotes: "Lighter version of dark mauve",
    kBands: [
      { center: 570, width: 65, amplitude: 1.0 },
      { center: 440, width: 50, amplitude: 0.3 },
    ],
    baseline: 0.03,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "bisque",
    name: "bisque",
    hex: "#f2cdcf",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PV19 + PW6 (very light)",
    pigmentNotes: "Very pale pink",
    kBands: [
      { center: 570, width: 65, amplitude: 1.0 },
      { center: 440, width: 50, amplitude: 0.3 },
    ],
    baseline: 0.03,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "raspberry-red",
    name: "raspberry red",
    hex: "#d1517a",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PR122 + PR254",
    pigmentNotes: "Alias of cranberry (shares hex)",
    kBands: [
      { center: 550, width: 60, amplitude: 1.0 },
      { center: 430, width: 50, amplitude: 0.4 },
      { center: 510, width: 50, amplitude: 0.4 },
      { center: 410, width: 50, amplitude: 0.2 },
    ],
    baseline: 0.042,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "fluorescent-red",
    name: "fluorescent red",
    hex: "#ff4c65",
    confidence: "fluorescent",
    mixingMethod: "kubelka_munk_fluorescent",
    pigmentGuess: "Rhodamine 6G or PR81 (PMA lake)",
    pigmentNotes: "Rhodamine 6G most likely; ex ~525nm, em ~555nm",
    kBands: [
      { center: 530, width: 40, amplitude: 1.0 },
      { center: 400, width: 30, amplitude: 0.3 },
    ],
    baseline: 0.04,
    kScale: 4.0,
    fluorescence: {
      exCenter: 530,
      exWidth: 35,
      emCenter: 565,
      emWidth: 40,
      quantumYield: 0.7,
    },
    kBandsSource: "pigment_template",
  },
  {
    id: "fluorescent-pink",
    name: "fluorescent pink",
    hex: "#ff48b0",
    confidence: "fluorescent",
    mixingMethod: "kubelka_munk_fluorescent",
    pigmentGuess: "Rhodamine B (BV10) or Rhodamine 6G (BR1)",
    pigmentNotes: "Rhodamine family; ex ~550nm, em ~590nm",
    kBands: [
      { center: 555, width: 40, amplitude: 1.0 },
      { center: 400, width: 30, amplitude: 0.3 },
    ],
    baseline: 0.04,
    kScale: 4.0,
    fluorescence: {
      exCenter: 555,
      exWidth: 35,
      emCenter: 595,
      emWidth: 40,
      quantumYield: 0.8,
    },
    kBandsSource: "pigment_template",
  },
  {
    id: "bubblegum",
    name: "bubblegum",
    hex: "#f984ca",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PR122 + PW6",
    pigmentNotes: "Bright pink, magenta family",
    kBands: [
      { center: 550, width: 60, amplitude: 1.0 },
      { center: 430, width: 50, amplitude: 0.4 },
    ],
    baseline: 0.03,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "mist",
    name: "mist",
    hex: "#d5e4c0",
    confidence: "low",
    mixingMethod: "alpha_blend_only",
    pigmentGuess: "PG7 + PW6 trace",
    pigmentNotes: "Very pale green-cream",
    kBands: [
      { center: 620, width: 50, amplitude: 0.165 },
      { center: 530, width: 50, amplitude: 0.106 },
      { center: 440, width: 50, amplitude: 0.247 },
    ],
    baseline: 0.02,
    kScale: 1.69,
    kBandsSource: "hex_synthesized",
  },
  {
    id: "metallic-gold",
    name: "metallic gold",
    hex: "#ac936e",
    confidence: "low",
    mixingMethod: "alpha_blend_only",
    pigmentGuess: "Bronze flake + PY74",
    pigmentNotes: "Metallic effect pigment; not modelable spectrally",
    kBands: [
      { center: 620, width: 50, amplitude: 0.325 },
      { center: 530, width: 50, amplitude: 0.424 },
      { center: 440, width: 50, amplitude: 0.569 },
    ],
    baseline: 0.02,
    kScale: 2.76,
    kBandsSource: "hex_synthesized",
  },
  {
    id: "bright-olive-green",
    name: "bright olive green",
    hex: "#b49f29",
    confidence: "low",
    mixingMethod: "alpha_blend_only",
    pigmentGuess: "PY74 + PBk7 + PG7 trace",
    pigmentNotes: "Yellow-olive",
    kBands: [
      { center: 620, width: 50, amplitude: 0.294 },
      { center: 530, width: 50, amplitude: 0.376 },
      { center: 440, width: 50, amplitude: 0.839 },
    ],
    baseline: 0.02,
    kScale: 3.01,
    kBandsSource: "hex_synthesized",
  },
  {
    id: "flat-gold",
    name: "flat gold",
    hex: "#bb8b41",
    confidence: "low",
    mixingMethod: "alpha_blend_only",
    pigmentGuess: "PY74 + PBr7 + PO34",
    pigmentNotes: "Muted gold; non-metallic",
    kBands: [
      { center: 620, width: 50, amplitude: 0.267 },
      { center: 530, width: 50, amplitude: 0.455 },
      { center: 440, width: 50, amplitude: 0.745 },
    ],
    baseline: 0.02,
    kScale: 2.96,
    kBandsSource: "hex_synthesized",
  },
  {
    id: "bright-gold",
    name: "bright gold",
    hex: "#ba8032",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PY74 + PO34",
    pigmentNotes: "Saturated yellow-orange gold",
    kBands: [
      { center: 430, width: 35, amplitude: 1.0 },
      { center: 380, width: 30, amplitude: 0.7 },
      { center: 480, width: 45, amplitude: 0.3 },
      { center: 400, width: 40, amplitude: 0.21 },
    ],
    baseline: 0.016,
    kScale: 8.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "copper",
    name: "copper",
    hex: "#bd6439",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PO34 + PBr7",
    pigmentNotes: "Bright orange-brown",
    kBands: [
      { center: 480, width: 45, amplitude: 1.0 },
      { center: 400, width: 40, amplitude: 0.7 },
      { center: 470, width: 80, amplitude: 0.3 },
      { center: 400, width: 50, amplitude: 0.27 },
      { center: 600, width: 100, amplitude: 0.15 },
    ],
    baseline: 0.035,
    kScale: 7.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "brick",
    name: "brick",
    hex: "#a75154",
    confidence: "low",
    mixingMethod: "alpha_blend_only",
    pigmentGuess: "PR101 + PR254",
    pigmentNotes: "Iron oxide red character",
    kBands: [
      { center: 620, width: 50, amplitude: 0.345 },
      { center: 530, width: 50, amplitude: 0.682 },
      { center: 440, width: 50, amplitude: 0.671 },
    ],
    baseline: 0.02,
    kScale: 3.26,
    kBandsSource: "hex_synthesized",
  },
  {
    id: "mahogany",
    name: "mahogany",
    hex: "#8e595a",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PBr7 + PR254",
    pigmentNotes: "Red-brown",
    kBands: [
      { center: 470, width: 80, amplitude: 1.0 },
      { center: 400, width: 50, amplitude: 0.9 },
      { center: 600, width: 100, amplitude: 0.5 },
      { center: 510, width: 50, amplitude: 0.3 },
      { center: 410, width: 50, amplitude: 0.15 },
    ],
    baseline: 0.059,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "brown",
    name: "brown",
    hex: "#925f52",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PBr7 + PY74",
    pigmentNotes: "Iron oxide brown + yellow",
    kBands: [
      { center: 470, width: 80, amplitude: 1.0 },
      { center: 400, width: 50, amplitude: 0.9 },
      { center: 600, width: 100, amplitude: 0.5 },
      { center: 430, width: 35, amplitude: 0.3 },
      { center: 380, width: 30, amplitude: 0.21 },
    ],
    baseline: 0.053,
    kScale: 5.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "white",
    name: "white",
    hex: "#ffffff",
    confidence: "certain",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PW6",
    pigmentNotes: "Titanium dioxide, disclosed in Riso SDS",
    kBands: [{ center: 400, width: 30, amplitude: 0.3 }],
    baseline: 0.0,
    kScale: 0.5,
    kBandsSource: "pigment_template",
  },
  {
    id: "clear-medium",
    name: "clear medium",
    hex: "#f2f2f2",
    confidence: "high",
    mixingMethod: "transparent",
    pigmentGuess: "none (carrier oil only)",
    pigmentNotes: "Transparent extender for tinting other inks",
    kBands: [],
    baseline: 0.0,
    kScale: 0.0,
    kBandsSource: "transparent_extender",
  },
  {
    id: "gray",
    name: "gray",
    hex: "#928d88",
    confidence: "high",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PBk7 (diluted)",
    pigmentNotes: "Diluted carbon black; tint variant",
    kBands: [{ center: 550, width: 1000, amplitude: 1.0 }],
    baseline: 0.0,
    kScale: 50.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "granite",
    name: "granite",
    hex: "#a5aaa8",
    confidence: "medium",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PBk7 + PW6",
    pigmentNotes: "Carbon black + titanium white",
    kBands: [
      { center: 550, width: 1000, amplitude: 1.0 },
      { center: 400, width: 30, amplitude: 0.06 },
    ],
    baseline: 0.0,
    kScale: 50.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "light-gray",
    name: "light gray",
    hex: "#88898a",
    confidence: "high",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PBk7 (heavily diluted)",
    pigmentNotes: "Same as gray, more transparent",
    kBands: [{ center: 550, width: 1000, amplitude: 1.0 }],
    baseline: 0.0,
    kScale: 50.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "charcoal",
    name: "charcoal",
    hex: "#70747c",
    confidence: "high",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PBk7 + PB15:3 trace",
    pigmentNotes: "Carbon black slightly cooled with phthalo",
    kBands: [
      { center: 550, width: 1000, amplitude: 1.0 },
      { center: 620, width: 50, amplitude: 0.1 },
      { center: 690, width: 30, amplitude: 0.07 },
      { center: 380, width: 50, amplitude: 0.03 },
    ],
    baseline: 0.002,
    kScale: 50.0,
    kBandsSource: "pigment_template",
  },
  {
    id: "black",
    name: "black",
    hex: "#000000",
    confidence: "certain",
    mixingMethod: "kubelka_munk",
    pigmentGuess: "PBk7",
    pigmentNotes: "Carbon black, disclosed in Riso SDS",
    kBands: [{ center: 550, width: 1000, amplitude: 1.0 }],
    baseline: 0.0,
    kScale: 50.0,
    kBandsSource: "pigment_template",
  },
];

export const INKS: readonly Ink[] = INKS_RAW.map((ink) => {
  // Calibrate KM params (kScale, baseline, per-band amplitudes) to match the
  // ink's hex at α=1. Raw values in the table are starting estimates; band
  // positions/widths stay fixed (those come from pigment chemistry).
  const cal = calibrateKScale(ink.hex, {
    kBands: ink.kBands,
    baseline: ink.baseline,
    kScale: ink.kScale,
    fluorescence: ink.fluorescence,
  });
  const calibratedBands = ink.kBands?.map((b, i) => ({
    ...b,
    amplitude: cal.amplitudes[i] ?? b.amplitude,
  }));
  const calibratedFluorescence =
    ink.fluorescence && cal.fluorescence
      ? { ...ink.fluorescence, ...cal.fluorescence }
      : ink.fluorescence;
  return {
    ...ink,
    rgb: hexToRgb(ink.hex),
    kBands: calibratedBands,
    baseline: cal.baseline,
    kScale: cal.kScale,
    fluorescence: calibratedFluorescence,
    kmDeltaE: cal.deltaE,
    kmEligible:
      cal.deltaE <=
      (ink.fluorescence
        ? KM_ELIGIBILITY_DELTA_E_FLUOR
        : KM_ELIGIBILITY_DELTA_E_NON_FLUOR),
  };
});

export const INKS_BY_ID: ReadonlyMap<string, Ink> = new Map(
  INKS.map((ink) => [ink.id, ink]),
);

// Known hex collisions in the source data — see file header. First occurrence
// wins; any *unexpected* collision should fail loudly at module load so a
// data edit can't silently shadow an existing ink.
const KNOWN_RGB_ALIASES: ReadonlySet<RgbU32> = new Set([
  hexToRgb("#914e72"), // burgundy / wine
  hexToRgb("#d2515e"), // tomato / marine red
  hexToRgb("#d1517a"), // cranberry / raspberry red
]);

export const INKS_BY_RGB: ReadonlyMap<RgbU32, Ink> = (() => {
  const map = new Map<RgbU32, Ink>();
  for (const ink of INKS) {
    const existing = map.get(ink.rgb);
    if (existing) {
      if (!KNOWN_RGB_ALIASES.has(ink.rgb)) {
        throw new Error(
          `unexpected duplicate hex ${ink.hex}: ${existing.id} vs ${ink.id}`,
        );
      }
      continue;
    }
    map.set(ink.rgb, ink);
  }
  return map;
})();

export const RISO_DEFAULTS: readonly string[] = [
  "bright-red",
  "fluorescent-pink",
  "yellow",
  "green",
  "blue",
  "black",
];
